version: "3.9"

services:
  first_node:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    environment:
      - SERVER_PORT=8080
      - ANOTHER_SERVERS=first_node:8085,second_node:8085,third_node:8085
    networks:
      - net

  second_node:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8081:8081"]
    environment:
      - SERVER_PORT=8081
      - ANOTHER_SERVERS=second_node:8085,first_node:8085,third_node:8085
    networks:
      - net
#    depends_on:
#     - first_node
  third_node:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8082:8082"]
    environment:
      - SERVER_PORT=8082
      - ANOTHER_SERVERS=third_node:8085,second_node:8085,first_node:8085
    networks:
      - net
#    depends_on:
#     - second_node


networks:
  net:
    driver: bridge
